export const weatherInfo = [

    {
        time: '6a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '28°',
        tempC: '-2°',
        // icon: 'Rainy.png',
        // description: 'Storm',
    },
    {
        time: '7a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '30°',
        tempC: '-1°',
        // icon: 'Rainy.png',
        // description: 'Storm',
    },
    {
        time: '8a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '32°',
        tempC: '0°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '9a',
        clouds: 1,
        rain: 0,
        snow: 0,
        tempF: '36°',
        tempC: '2°',
        // icon: 'Lightning.png',
        // description: 'Storm',
    },
    {
        time: '10a',
        clouds: 1,
        rain: 0,
        snow: 0,
        tempF: '38°',
        tempC: '3°',
        // icon: 'Lightning.png',
        // description: 'Storm',
    },
    {
        time: '11a',
        clouds: 1,
        rain: 0,
        snow: 0,
        tempF: '39°',
        tempC: '4°',
        // icon: 'Lightning.png',
        // description: 'Storm',
    },
    {
        time: '12a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '42°',
        tempC: '5.5°',
        // icon: 'Sunny.png',
        // description: 'Storm',
    },
    {
        time: '1p',
        clouds: 0,
        rain: 1,
        snow: 0,
        tempF: '42°',
        tempC: '5.5°',
        // icon: 'Sunny.png',
        // description: 'Storm',
    },
    {
        time: '2p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '41°',
        tempC: '5°',
        // icon: 'Lightning.png',
        // description: 'Storm',
    },
    {
        time: '3p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '40°',
        tempC: '4.5°',
        // icon: 'Partly_sunny.png',
        // description: 'Storm',
    },
    {
        time: '4p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '39°',
        tempC: '4°',
        // icon: 'Partly_sunny.png',
        // description: 'Storm',
    },
    {
        time: '5p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '38°',
        tempC: '3.3°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '6p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '36°',
        tempC: '2°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '7p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '34°',
        tempC: '1°',
        // icon: 'Rainy.png',
        // description: 'Storm',
    },
    {
        time: '8p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '33°',
        tempC: '0.5°',
        // icon: 'Rainy.png',
        // description: 'Storm',
    },
    {
        time: '9p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '30°',
        tempC: '-1°',
        // icon: 'Rainy.png',
        // description: 'Storm',
    },
    {
        time: '10p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '27°',
        tempC: '-2.7°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '11p',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '25°',
        tempC: '-4°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '12p',
        clouds: 0,
        rain: 0,
        snow: 0,
        // icon: 'Snowing.png',
        // description: 'Storm',
        tempF: '24°',
        tempC: '-4.5°',
    },
    {
        time: '1a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '22°',
        tempC: '-5.5°',
        // icon: 'Snowing.png',
        // description: 'Storm',
    },
    {
        time: '2a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '19°',
        tempC: '-7°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '3a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '20°',
        tempC: '-6.6°',
        // icon: 'Lightning.png',
        // description: 'Storm',
    },
    {
        time: '4a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '23°',
        tempC: '-5°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
    {
        time: '5a',
        clouds: 0,
        rain: 0,
        snow: 0,
        tempF: '26°',
        tempC: '-3°',
        // icon: 'Cloudy.png',
        // description: 'Storm',
    },
];